### ISSUE TITLE
Calculate number of volunteers required

### ISSUE THREAD

**Issue by Elynor-Kamil** [Elynor-Kamil/2021-Emergency-Management-System#17]
Calculate number of volunteers required
Based on number of refugees
May be a range instead of a specific number
Simple way: fixed ratio
Complex way: data-driven/model-based

**Comment by michellechan1123** [comment]
#17 optional separate function with #7. 

#17
- ratio: 1:20 (aka remaining volunteers required) 
- due: 19/11

- add the result into the dict to the dict[camp]: list[-1]

#7 
- extract refugee and volunteers from local document (demodocument)
- loop through blocks to calculate sum (?) and store it as dict (key: camp, value:[numofrefugees, numofvolunteers])

**Comment by michellechan1123** [comment]
#7 
exception if user types in 
1. plans does not exist 
2. plans do exist but archived

Only with dealing with it before calling #7 and #17

**Comment by Elynor-Kamil** [comment]
If the ratio produces a fraction of volunteers then round up to the nearest whole number

e.g. if ratio deduces 1.3 volunteers needed, round up to 2 volunteers needed

**Comment by michellechan1123** [comment]
#7 and #17
- admin read permission

- store refugees and volunteers in corresponding camp
- fetch len(refugee) and len(volunteer) from camps in a targeted plan
- arrange these results using ReferenceDocumentsField from models.base.field (parent='plan', children='camp': list[refugeeNum, volunteerNum])

- by using the table created above, can perform #17 feature -> calculate remaining_volunteer and extra_volunteer_required
- consequently, add those calculated results into the table
